Vagrant.configure("2") do |config|
  # Box image and its version
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8081" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024" # Allocate 1GB of RAM to the VM
    vb.cpus = 1  # Allocate 1 cpu core to the VM
  end

  # Syncing host and guest folders. Important for sourcing bash scripts 
  # when 'install.sh' is being provisioned.
  config.vm.synced_folder ".", "/vagrant"

  # Enable provisioning with a shell script. 
  config.vm.provision "shell", path: "./scripts/install.sh"
end
